# Generated by Django 4.2.20 on 2025-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_customuser_address_alter_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='return_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата возврата'),
        ),
    ]
