# Generated by Django 4.2.20 on 2025-04-24 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_book_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Автор книги, не более 255 символов', max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(help_text='Язык книги, не более 100 символов', max_length=100, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(help_text='Название книги, не более 255 символов', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(blank=True, help_text='Первая дата публикации книги или примерный век, не более 100 символов', max_length=100, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reader',
            field=models.ForeignKey(blank=True, help_text='Читатель данной книги', limit_choices_to={'role': 'READER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
    ]
