# Generated by Django 4.2.20 on 2025-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_book_author_alter_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='return_date',
            field=models.DateField(blank=True, help_text='Дата, когда читетль должен вернуть книгу', null=True, verbose_name='Дата возврата'),
        ),
    ]
