# Generated by Django 4.2.20 on 2025-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_alter_book_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='book',
            name='printing_year',
            field=models.IntegerField(blank=True, help_text='Год издания', null=True, verbose_name='Год издания'),
        ),
    ]
