# Generated by Django 4.2.20 on 2025-04-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_remove_book_return_date_book_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isReserved',
            new_name='is_taken',
        ),
    ]
