# Generated by Django 4.2.20 on 2025-04-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_rename_isreserved_book_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата конца выдачи/брони', null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_taken',
            field=models.BooleanField(default=False, help_text='Книга взята читателем или нет', verbose_name='Забронирована'),
        ),
    ]
