# Generated by Django 4.2.20 on 2025-04-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_alter_book_end_date_alter_book_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='end_date',
            field=models.DateField(blank=True, help_text='Если книга взята, то это дата конца выдачи. Если книга не взята, то это конец брони', null=True, verbose_name='Дата конца выдачи/брони'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_taken',
            field=models.BooleanField(default=False, help_text='Книга взята читателем или нет', verbose_name='На руках'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
